name: ai_expense_tracker
description: เหมียวตังค์ (MeowTang) - แอพบันทึกรายรับรายจ่าย วางแผนงบประมาณ & สแกนสลิปอัจฉริยะ
publish_to: 'none'

version: 1.41.17+60

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  google_fonts: ^8.2.1
  intl: ^0.20.3
  path_provider: ^2.1.6
  pdf: ^3.11.1
  qr: ^3.0.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/banks/
    - assets/icon/
    - assets/fonts/