import '../models/transaction_item.dart';

class DuplicateSlipChecker {
  static const genericNames = {
    'image.jpg', 'image.png', 'image.jpeg', 'download.jpg', 'download.png',
    'slip.jpg', 'slip.png', 'photo.jpg', 'temp.jpg'
  };

  /// Extracts clean filename/basename from a path or URI
  static String extractBasename(String? pathOrUri) {
    if (pathOrUri == null || pathOrUri.trim().isEmpty) return '';
    final clean = pathOrUri.trim().replaceAll('\\', '/').split('?').first;
    final lastSegment = clean.split('/').last.trim().toLowerCase();
    return lastSegment;
  }

  /// Checks if a slip or transaction is already recorded in the database or was previously deleted.
  ///
  /// Pass [index] (built once with [SlipIndex.from]) when checking many slips
  /// against the same transactions: only the transactions that could match
  /// are compared, instead of walking the whole list for every slip.
  static bool isDuplicate({
    required List<TransactionItem> existingTransactions,
    List<String>? deletedSlipIdentifiers,
    List<String>? importedSlipIdentifiers,
    Set<String>? cachedDeletedSet,
    Set<String>? cachedImportedSet,
    String? filePath,
    String? fileName,
    String? refId,
    double? amount,
    DateTime? date,
    String? bankName,
    String? excludeId,
    SlipIndex? index,
  }) {
    final cleanPath = (filePath?.trim().toLowerCase() ?? '').replaceAll('\\', '/');
    final baseName1 = extractBasename(fileName);
    final baseName2 = extractBasename(filePath);
    final effectiveName = baseName1.isNotEmpty ? baseName1 : baseName2;

    final cleanRef = refId?.trim().toLowerCase() ?? '';
    final isAutoGeneratedRef = cleanRef.isEmpty || cleanRef.startsWith('slip-') || cleanRef.startsWith('no-qr-');

    // 0. Check against Deleted Slips Registry (Persistent Ignore List)
    final Set<String>? deletedSet = cachedDeletedSet ??
        (deletedSlipIdentifiers != null && deletedSlipIdentifiers.isNotEmpty
            ? deletedSlipIdentifiers.map((s) => s.trim().toLowerCase()).toSet()
            : null);
    if (deletedSet != null && deletedSet.isNotEmpty) {
      if (cleanPath.isNotEmpty && deletedSet.contains(cleanPath)) {
        return true;
      }
      if (effectiveName.isNotEmpty && deletedSet.contains(effectiveName)) {
        return true;
      }
      if (!isAutoGeneratedRef && cleanRef.isNotEmpty && deletedSet.contains(cleanRef)) {
        return true;
      }
      if (amount != null && amount > 0 && date != null) {
        final fp = 'fp_${amount}_${date.year}_${date.month}_${date.day}_${date.hour}_${date.minute}'.toLowerCase();
        if (deletedSet.contains(fp)) {
          return true;
        }
      }
    }

    // 0.5. Check against Imported Slips Registry (Persistent Scanned History)
    final Set<String>? importedSet = cachedImportedSet ??
        (importedSlipIdentifiers != null && importedSlipIdentifiers.isNotEmpty
            ? importedSlipIdentifiers.map((s) => s.trim().toLowerCase()).toSet()
            : null);
    if (importedSet != null && importedSet.isNotEmpty) {
      if (cleanPath.isNotEmpty && importedSet.contains(cleanPath)) {
        return true;
      }
      if (effectiveName.isNotEmpty && importedSet.contains(effectiveName)) {
        return true;
      }
      if (!isAutoGeneratedRef && cleanRef.isNotEmpty && importedSet.contains(cleanRef)) {
        return true;
      }
    }

    final candidates = index != null
        ? index._candidates(cleanPath: cleanPath, name: effectiveName, ref: cleanRef, amount: amount)
        : existingTransactions.map(_SlipTxKey.of);

    for (final key in candidates) {
      final tx = key.tx;
      if (excludeId != null && tx.id == excludeId) {
        continue;
      }

      final txPath = key.path;
      final txBaseName = key.baseName;
      final txRef = key.ref;
      final isTxRefAutoGenerated = txRef.isEmpty || txRef.startsWith('slip-') || txRef.startsWith('no-qr-');

      // Authentic Bank Ref Check: If BOTH have authentic refId and they differ, they are GUARANTEED NOT duplicates!
      final bool hasDistinctAuthenticRefs = !isAutoGeneratedRef &&
          !isTxRefAutoGenerated &&
          cleanRef.isNotEmpty &&
          txRef.isNotEmpty &&
          cleanRef != txRef;

      if (hasDistinctAuthenticRefs) {
        // Different bank transactions! Never flag as duplicate against this tx.
        continue;
      }

      // 1. Exact or Normalized Path Match
      if (cleanPath.isNotEmpty && txPath.isNotEmpty) {
        if (txPath == cleanPath) {
          return true;
        }
      }

      // 2. Exact Filename / Basename Match (Skip generic names like image.jpg, download.jpg, slip.png)
      final isGeneric = genericNames.contains(effectiveName.toLowerCase());

      if (effectiveName.isNotEmpty && !isGeneric) {
        if (txBaseName.isNotEmpty) {
          if (txBaseName == effectiveName || txBaseName.endsWith('_$effectiveName') || txBaseName.endsWith(effectiveName)) {
            return true;
          }
        }
        if (txPath.isNotEmpty) {
          if (txPath.endsWith(effectiveName) || txPath.contains('/$effectiveName') || txPath.contains('_$effectiveName')) {
            return true;
          }
        }
        if (key.note.isNotEmpty && key.note.contains(effectiveName)) {
          return true;
        }
      }

      // 3. Bank Reference ID Match (only for authentic bank ref IDs, not auto SLIP-timestamp)
      if (!isAutoGeneratedRef && !isTxRefAutoGenerated && cleanRef.isNotEmpty) {
        if (txRef == cleanRef) {
          return true;
        }
      }

      // 4. Amount + Time + Transaction details Match
      if (amount != null && tx.amount == amount) {
        if (date != null) {
          // Special case: Amount 0.0 with same bank on same day
          if (amount == 0.0) {
            if (tx.date.year == date.year && tx.date.month == date.month && tx.date.day == date.day) {
              if (bankName != null && tx.bankName != null && bankName.isNotEmpty && tx.bankName!.isNotEmpty) {
                final b1 = bankName.toLowerCase().replaceAll(RegExp(r'[\s\(\)\-_]'), '');
                final b2 = tx.bankName!.toLowerCase().replaceAll(RegExp(r'[\s\(\)\-_]'), '');
                if (b1.contains(b2) || b2.contains(b1)) {
                  return true;
                }
              }
            }
          } else if (amount > 0) {
            final diffSeconds = (tx.date.difference(date).inSeconds).abs();
            // If identical slip image or identical path and within 2 minutes:
            final bool sameImageEvidence = (cleanPath.isNotEmpty && txPath.isNotEmpty && cleanPath == txPath) ||
                (effectiveName.isNotEmpty && txBaseName.isNotEmpty && effectiveName == txBaseName);

            if (sameImageEvidence && diffSeconds < 300) {
              return true;
            }

            // Same exact second with same amount and same bank (exact double submission)
            if (diffSeconds <= 1 && tx.bankName == bankName) {
              return true;
            }
          }
        }
      }
    }

    return false;
  }
}

/// A transaction's slip fields, normalised once.
class _SlipTxKey {
  final TransactionItem tx;
  final String path;
  final String baseName;
  final String ref;
  final String note;

  _SlipTxKey(this.tx, this.path, this.baseName, this.ref, this.note);

  factory _SlipTxKey.of(TransactionItem tx) => _SlipTxKey(
        tx,
        (tx.slipImageUrl?.trim().toLowerCase() ?? '').replaceAll('\\', '/'),
        DuplicateSlipChecker.extractBasename(tx.slipImageUrl),
        tx.slipRefId?.trim().toLowerCase() ?? '',
        tx.note?.toLowerCase() ?? '',
      );
}

/// Lookup tables over existing transactions so duplicate checks during a slip
/// scan cost about the same no matter how many transactions are saved.
///
/// [_candidates] returns every transaction that [DuplicateSlipChecker.isDuplicate]
/// could match: same path, same file name (or a saved copy named
/// `slip_<hash>_<name>`), same bank reference, same amount, or a note that
/// mentions an image file. The full per-transaction rules still run on them.
class SlipIndex {
  final _byPath = <String, List<_SlipTxKey>>{};
  final _byName = <String, List<_SlipTxKey>>{};
  final _byRef = <String, List<_SlipTxKey>>{};
  final _byAmount = <double, List<_SlipTxKey>>{};
  final _withFileNote = <_SlipTxKey>[];

  SlipIndex.from(Iterable<TransactionItem> transactions) {
    transactions.forEach(add);
  }

  void add(TransactionItem tx) {
    final key = _SlipTxKey.of(tx);
    void put<K>(Map<K, List<_SlipTxKey>> map, K k) => (map[k] ??= []).add(key);

    if (key.path.isNotEmpty) put(_byPath, key.path);
    if (key.baseName.isNotEmpty) {
      put(_byName, key.baseName);
      // Every "_"-separated suffix, so "slip_123_abc.jpg" is found by "abc.jpg".
      var i = key.baseName.indexOf('_');
      while (i != -1 && i + 1 < key.baseName.length) {
        put(_byName, key.baseName.substring(i + 1));
        i = key.baseName.indexOf('_', i + 1);
      }
    }
    if (key.ref.isNotEmpty) put(_byRef, key.ref);
    put(_byAmount, tx.amount);
    if (key.note.contains('.jpg') || key.note.contains('.jpeg') || key.note.contains('.png') || key.note.contains('.webp')) {
      _withFileNote.add(key);
    }
  }

  Iterable<_SlipTxKey> _candidates({required String cleanPath, required String name, required String ref, double? amount}) {
    final seen = <_SlipTxKey>{};
    void addAll(List<_SlipTxKey>? list) {
      if (list != null) seen.addAll(list);
    }

    if (cleanPath.isNotEmpty) addAll(_byPath[cleanPath]);
    if (name.isNotEmpty) addAll(_byName[name]);
    if (ref.isNotEmpty) addAll(_byRef[ref]);
    if (amount != null) addAll(_byAmount[amount]);
    seen.addAll(_withFileNote);
    return seen;
  }
}
