import '../models/transaction_item.dart';

class DuplicateSlipChecker {
  /// Extracts clean filename/basename from a path or URI
  static String extractBasename(String? pathOrUri) {
    if (pathOrUri == null || pathOrUri.trim().isEmpty) return '';
    final clean = pathOrUri.trim().replaceAll('\\', '/').split('?').first;
    final lastSegment = clean.split('/').last.trim().toLowerCase();
    return lastSegment;
  }

  /// Checks if a slip or transaction is already recorded in the database or was previously deleted
  static bool isDuplicate({
    required List<TransactionItem> existingTransactions,
    List<String>? deletedSlipIdentifiers,
    List<String>? importedSlipIdentifiers,
    String? filePath,
    String? fileName,
    String? refId,
    double? amount,
    DateTime? date,
    String? bankName,
    String? excludeId,
  }) {
    final cleanPath = (filePath?.trim().toLowerCase() ?? '').replaceAll('\\', '/');
    final baseName1 = extractBasename(fileName);
    final baseName2 = extractBasename(filePath);
    final effectiveName = baseName1.isNotEmpty ? baseName1 : baseName2;

    final cleanRef = refId?.trim().toLowerCase() ?? '';
    final isAutoGeneratedRef = cleanRef.isEmpty || cleanRef.startsWith('slip-') || cleanRef.startsWith('no-qr-');

    // 0. Check against Deleted Slips Registry (Persistent Ignore List)
    if (deletedSlipIdentifiers != null && deletedSlipIdentifiers.isNotEmpty) {
      final deletedSet = deletedSlipIdentifiers.map((s) => s.trim().toLowerCase()).toSet();

      if (cleanPath.isNotEmpty && deletedSet.contains(cleanPath)) {
        return true;
      }
      if (effectiveName.isNotEmpty && deletedSet.contains(effectiveName)) {
        return true;
      }
      if (!isAutoGeneratedRef && cleanRef.isNotEmpty && deletedSet.contains(cleanRef)) {
        return true;
      }
      if (amount != null && amount > 0 && date != null) {
        final fp = 'fp_${amount}_${date.year}_${date.month}_${date.day}_${date.hour}_${date.minute}'.toLowerCase();
        if (deletedSet.contains(fp)) {
          return true;
        }
      }
    }

    // 0.5. Check against Imported Slips Registry (Persistent Scanned History)
    if (importedSlipIdentifiers != null && importedSlipIdentifiers.isNotEmpty) {
      final importedSet = importedSlipIdentifiers.map((s) => s.trim().toLowerCase()).toSet();

      if (cleanPath.isNotEmpty && importedSet.contains(cleanPath)) {
        return true;
      }
      if (effectiveName.isNotEmpty && importedSet.contains(effectiveName)) {
        return true;
      }
      if (!isAutoGeneratedRef && cleanRef.isNotEmpty && importedSet.contains(cleanRef)) {
        return true;
      }
    }

    for (final tx in existingTransactions) {
      if (excludeId != null && tx.id == excludeId) {
        continue;
      }

      final txPath = (tx.slipImageUrl?.trim().toLowerCase() ?? '').replaceAll('\\', '/');
      final txBaseName = extractBasename(tx.slipImageUrl);
      final txRef = tx.slipRefId?.trim().toLowerCase() ?? '';
      final isTxRefAutoGenerated = txRef.isEmpty || txRef.startsWith('slip-') || txRef.startsWith('no-qr-');

      // Authentic Bank Ref Check: If BOTH have authentic refId and they differ, they are GUARANTEED NOT duplicates!
      final bool hasDistinctAuthenticRefs = !isAutoGeneratedRef &&
          !isTxRefAutoGenerated &&
          cleanRef.isNotEmpty &&
          txRef.isNotEmpty &&
          cleanRef != txRef;

      if (hasDistinctAuthenticRefs) {
        // Different bank transactions! Never flag as duplicate against this tx.
        continue;
      }

      // 1. Exact or Normalized Path Match
      if (cleanPath.isNotEmpty && txPath.isNotEmpty) {
        if (txPath == cleanPath) {
          return true;
        }
      }

      // 2. Exact Filename / Basename Match (Skip generic names like image.jpg, download.jpg, slip.png)
      final genericNames = {'image.jpg', 'image.png', 'image.jpeg', 'download.jpg', 'download.png', 'slip.jpg', 'slip.png', 'photo.jpg', 'temp.jpg'};
      final isGeneric = genericNames.contains(effectiveName.toLowerCase());

      if (effectiveName.isNotEmpty && !isGeneric) {
        if (txBaseName.isNotEmpty) {
          if (txBaseName == effectiveName || txBaseName.endsWith('_$effectiveName') || txBaseName.endsWith(effectiveName)) {
            return true;
          }
        }
        if (txPath.isNotEmpty) {
          if (txPath.endsWith(effectiveName) || txPath.contains('/$effectiveName') || txPath.contains('_$effectiveName')) {
            return true;
          }
        }
        if (tx.note != null && tx.note!.toLowerCase().contains(effectiveName)) {
          return true;
        }
      }

      // 3. Bank Reference ID Match (only for authentic bank ref IDs, not auto SLIP-timestamp)
      if (!isAutoGeneratedRef && !isTxRefAutoGenerated && cleanRef.isNotEmpty) {
        if (txRef == cleanRef) {
          return true;
        }
      }

      // 4. Amount + Time + Transaction details Match
      if (amount != null && tx.amount == amount) {
        if (date != null) {
          // Special case: Amount 0.0 with same bank on same day
          if (amount == 0.0) {
            if (tx.date.year == date.year && tx.date.month == date.month && tx.date.day == date.day) {
              if (bankName != null && tx.bankName != null && bankName.isNotEmpty && tx.bankName!.isNotEmpty) {
                final b1 = bankName.toLowerCase().replaceAll(RegExp(r'[\s\(\)\-_]'), '');
                final b2 = tx.bankName!.toLowerCase().replaceAll(RegExp(r'[\s\(\)\-_]'), '');
                if (b1.contains(b2) || b2.contains(b1)) {
                  return true;
                }
              }
            }
          } else if (amount > 0) {
            final diffSeconds = (tx.date.difference(date).inSeconds).abs();
            // If identical slip image or identical path and within 2 minutes:
            final bool sameImageEvidence = (cleanPath.isNotEmpty && txPath.isNotEmpty && cleanPath == txPath) ||
                (effectiveName.isNotEmpty && txBaseName.isNotEmpty && effectiveName == txBaseName);

            if (sameImageEvidence && diffSeconds < 300) {
              return true;
            }

            // Same exact second with same amount and same bank (exact double submission)
            if (diffSeconds <= 1 && tx.bankName == bankName) {
              return true;
            }
          }
        }
      }
    }

    return false;
  }
}
